In [2]:
#tuples
tuple1=("sachin","saurav","dhoni")
print(tuple1[0])
for x in tuple1:
    print(x)
    
#accessing values in tuple

tup2=(1,2,3,4,5,6)
print(tup2[1:5])

sachin
sachin
saurav
dhoni
(2, 3, 4, 5)


In [3]:
import numpy as np
#1D array
arr1=np.array([1,2,3])
print(arr1)
print(type(arr1))
print(arr1.dtype)
print(arr1[0])

#nd array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2[0,1])
print(arr2.ndim)

[1 2 3]
<class 'numpy.ndarray'>
int32
1
[[1 2 3]
 [4 5 6]]
2
2


In [4]:
arr2=np.array([(9),(2)])
print(arr2)
print(arr2.ndim)
arr2=np.array([(9,),(2,)])
print(arr2)
print(arr2.ndim)

[9 2]
1
[[9]
 [2]]
2


In [15]:
import numpy as np
#data_types
arr3=np.array([9,2],dtype=float)
print(arr3)
print(arr3.dtype)

[9. 2.]
float64


In [6]:
#shape returns tuple consisting of array dimensions

arr1=np.array([[10,20],[30,40],[30,40]])
print(arr1.shape)
print(arr1)

(3, 2)
[[10 20]
 [30 40]
 [30 40]]


In [7]:
#resize the shapes

arr1=np.array([[10,20,30],[50,30,40]])
print(arr1.shape)
arr1.shape=(3,2)
print(arr1.shape)

print(arr1)

(2, 3)
(3, 2)
[[10 20]
 [30 50]
 [30 40]]


In [19]:
#reshape
b=arr1.reshape(2,3)
print(b)
print("\n",arr1)

[[10 20 30]
 [50 30 40]]

 [[10 20]
 [30 50]
 [30 40]]


In [6]:
#empty()--> creates an uninitialized array
arr1=np.empty([3,2],dtype=int)
print("Filled with random values :\n",arr1) #filled with random values

#zeros-->creates an array filled with zeroes

arr2=np.zeros([3,2])
print("filled with zeroes: \n",arr2)

arr2=np.zeros([3,2],dtype=int) #default data-type is float, now changed to int

print("filled with zeroes: \n",arr2)

# print array with ones
arr2=np.ones([3,2],dtype=int)

print("filled with 1: \n",arr2)

Filled with random values :
 [[0 0]
 [0 0]
 [0 0]]
filled with zeroes: 
 [[0. 0.]
 [0. 0.]
 [0. 0.]]
filled with zeroes: 
 [[0 0]
 [0 0]
 [0 0]]
filled with 1: 
 [[1 1]
 [1 1]
 [1 1]]


In [7]:
#nd array from list of tuple
list1=[(1,2,3),(4,5,6)]
arr4=np.array(list1)
print("Dimension of array :",arr4.ndim)
print("array from list of tuples:\n",arr4)

Dimension of array : 2
array from list of tuples:
 [[1 2 3]
 [4 5 6]]


In [20]:
import numpy as np

#arange-->evenly spaced numbers from range

arr1=np.arange(10) #upper bound not included
print(arr1)

arr2=np.arange(10,dtype=float)
print(arr2)

arr3=np.arange(2,10,2)
print(arr3) #start,stop,step

#linspace--> instead of step,the number of interval is uniform

arr4=np.linspace(2,10,4)#end-point is to include the upper bound...here start,stop,any 'n' numbers
print("upper bound included :",arr4)

arr4=np.linspace(2,10,3,endpoint=False,dtype=int)
print("upper bound not included : ",arr4)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[2 4 6 8]
upper bound included : [ 2.          4.66666667  7.33333333 10.        ]
upper bound not included :  [2 4 7]


In [8]:
#array slicing

arr1=np.arange(10)

print("2. after slicing :",arr1[2:9:1])#here 'values' are passed not 'INDEX'
print("3. after slicing :",arr1[2:])#here 'values' are passed not 'INDEX'

#slicing for ndarray
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("4. after slicing : \n",arr2[:,1:])#first argument is for rows to select, and second argument for columns

2. after slicing : [2 3 4 5 6 7 8]
3. after slicing : [2 3 4 5 6 7 8 9]
4. after slicing : 
 [[2 3]
 [5 6]
 [8 9]]


In [9]:
#using ellipses
arr4=np.array([[1,2,3,4],[4,5,6,10],[7,8,9,11]])
print("demo of ellipses")
print("-----------")
#(...) indicates every,first argument is for rows and second is for columns
print("5. after slicing :",arr4[...,1])
print("6. after slicing :",arr4[2,...])
print("7. after slicing :\n",arr4[...,1:])

demo of ellipses
-----------
5. after slicing : [2 5 8]
6. after slicing : [ 7  8  9 11]
7. after slicing :
 [[ 2  3  4]
 [ 5  6 10]
 [ 8  9 11]]


In [33]:
#integer indexing
arr5=np.array([[1,2,3],[4,5,6],[7,8,9]])
y=arr5[[0,1,2],[1,0,2]] #combinations of pairs (0,1)(1,0)(2,2)
print(y)
y=arr5[[0,2],[0,2]]
print("corner elements :",y)

[2 4 9]
corner elements : [1 9]


In [22]:
#broadcasting when operations of multiple arrays with shape
arr7=np.array([[10,20,30],[2,3,4]])
arr8=np.array([[40,30,20],[7,6,5]])
print("Multiplication on arrays of same shape :",arr7*arr8)

#smaller array is broadcasted to larger array

arr8=np.array([[1,1,1],[20,30,40],[50,60,70]])
arr9=np.array([1,2,3])
print("array after addition :",arr8+arr9)

Multiplication on arrays of same shape : [[400 600 600]
 [ 14  18  20]]
array after addition : [[ 2  3  4]
 [21 32 43]
 [51 62 73]]


In [10]:
#concatenate
arr1=np.array([[2,3],[4,5]])
arr2=np.array([[6,7],[8,9]])
resarr=np.concatenate((arr1,arr2))#default axis=0
print("concatenate along 0 axis :\n",resarr)
resarr=np.concatenate(((arr1,arr2)),axis=1)
print("concatenate along 1 axis :\n",resarr)

concatenate along 0 axis :
 [[2 3]
 [4 5]
 [6 7]
 [8 9]]
concatenate along 1 axis :
 [[2 3 6 7]
 [4 5 8 9]]


In [37]:
#split
arr3=np.arange(9)
print("whole array :",arr3)
arr4=np.split(arr3,3)
print("after splitting in 3 equal sized axis: ",arr4)

whole array : [0 1 2 3 4 5 6 7 8]
after splitting in 3 equal sized axis:  [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [15]:
#append elements
arr4=np.arange(9)
arr4=arr4.reshape(3,3)
print("before appending :\n",arr4)
arr5=np.append(arr4,[10,11,12])
print("\nafter appending :",arr5)
arr6=np.append(arr4,[[10,11,12],[13,14,15],[16,17,18]],axis=1)
print("\nappended at axis 1 :\n",arr6)
arr6=np.append(arr4,[[10,11,12]],axis=0)
print("\nappended at axis 0 :\n",arr6)

before appending :
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

after appending : [ 0  1  2  3  4  5  6  7  8 10 11 12]

appended at axis 1 :
 [[ 0  1  2 10 11 12]
 [ 3  4  5 13 14 15]
 [ 6  7  8 16 17 18]]

appended at axis 0 :
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [10 11 12]]


In [19]:
#insert at specific location
arr4=np.arange(9)
arr4=arr4.reshape(3,3)
print("ARR4:\n",arr4)
arr7=np.insert(arr4,3,199)
print("\nAxis parameter not passed hence flattened :",arr7)
arr8=np.insert(arr4,3,[11],axis=0)
print("\ninserted at 3rd index on 0 axis : \n",arr8)
arr9=np.insert(arr4,3,[290],axis=1)
print("\ninserted at 3rd index in 1 axis : \n",arr9)

ARR4:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Axis parameter not passed hence flattened : [  0   1   2 199   3   4   5   6   7   8]

inserted at 3rd index on 0 axis : 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [11 11 11]]

inserted at 3rd index in 1 axis : 
 [[  0   1   2 290]
 [  3   4   5 290]
 [  6   7   8 290]]
