In [5]:
#remove
import numpy as np
arr4=np.arange(9)
arr4=arr4.reshape(3,3)
arr10=np.delete(arr4,3)
print("array flattened before deleting as axis is not mentioned :",arr10)
arr11=np.delete(arr4,2,axis=0)
print("element deleted along axis 0 :\n",arr11)
print("\nOriginally:\n",arr4)
arr11=np.delete(arr4,2,axis=1)
print("element deleted along axis 1 :\n",arr11)

array flattened before deleting as axis is not mentioned : [0 1 2 4 5 6 7 8]
element deleted along axis 0 :
 [[0 1 2]
 [3 4 5]]

Originally:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
element deleted along axis 1 :
 [[0 1]
 [3 4]
 [6 7]]


In [5]:
#methods---> .add, .subtract, .multiply, .divide

In [8]:
#median

arr3=np.array([[1,10,11],[20,30,40],[31,21,15]])
print(arr3)

arr4=np.mean(arr3,axis=1)
print("\nmean along row:",arr4)
list1=[]
m=np.sort(arr4)

for i in m:
    for j in arr3:
        if np.mean(j,axis=0)==i: #matching means with sorted means
            list1.append(j)
print("\nSorted array wrt means in ascending order :","\n",list1)

[[ 1 10 11]
 [20 30 40]
 [31 21 15]]

mean along row: [ 7.33333333 30.         22.33333333]

Sorted array wrt means in ascending order : 
 [array([ 1, 10, 11]), array([31, 21, 15]), array([20, 30, 40])]


In [ ]:
#series
